Update aserto-dotnet sdk documentation
aserto-dev/topaz-website pull request #143
Opened 2024-09-23 15:33 UTC by carabasdaniel

2024-09-24 09:27 UTC, gertd commented on docs/software-development-kits/dotnet/dotnetcore.mdx
> +Configure the Policy root and Policy ID in the `appsettings.json`:
Is `Policy ID` correct, we no longer use policy IDs, nor do I see it in the appsettings?

2024-09-24 09:30 UTC, gertd requested changes
See questions in the comments

2024-09-26 16:58 UTC, gertd approved these changes

2024-11-06 01:42 UTC, ogazitt approved these changes

2024-11-06 14:36 UTC, merged